spring:
  application:
    name: meshtastic-forwarder-client
# use a different port than the server for spring
server:
  port: 8081
# expose health endpoint
management:
  endpoints:
    web:
      exposure:
        include: health
# meshtastic config
meshtastic:
  client:
    # `MESHTASTIC_CLIENT_BASEURL` env var overrides this
    base-url: 127.0.0.1:8080
    # `MESHTASTIC_CLIENT_TOKEN` env var overrides this
    token: dev-token
    # `MESHTASTIC_CLIENT_ENABLETLS` env var overrides this
    enable-tls: false
    # features
    features:
      # enable debug reply on primary channel
      # MESHTASTIC_CLIENT_FEATURES_ENABLEDEBUGREPLYONPRIMARYCHANNEL
      enable-debug-reply-on-primary-channel: true

      # enable gemini on private chat
      # MESHTASTIC_CLIENT_FEATURES_ENABLEGEMINIONPRIVATECHAT
      enable-gemini-on-private-chat: true

      # enable gemini on public chat
      # MESHTASTIC_CLIENT_FEATURES_ENABLEGEMINIONPUBLICCHAT
      enable-gemini-on-public-chat: true

      # gemini enabled channel indexes, comma separated integer values
      public-gemini-enabled-channel-indexes: 0
