spring:
  application:
    name: meshtastic-forwarder-client
# use a different port than the server for spring
server:
  port: 8081
# expose health endpoint
management:
  endpoints:
    web:
      exposure:
        include: health
# meshtastic config
meshtastic:
  client:
    # `MESHTASTIC_CLIENT_BASEURL` env var overrides this
    base-url: 127.0.0.1:8080
    # `MESHTASTIC_CLIENT_TOKEN` env var overrides this
    token: dev-token
    # `MESHTASTIC_CLIENT_ENABLETLS` env var overrides this
    enable-tls: false
# OpenAI config, will configure proxy if HTTP_PROXY is set (only support HTTP, no HTTPS yet).
openai:
  # default to google gemini (AI studio), use `OPENAI_BASEURL` to override
  base-url: https://generativelanguage.googleapis.com/v1beta/openai/
  # default read GEMINI_API_KEY from env var, use `OPENAI_APIKEY` to override
  api-key: ${GEMINI_API_KEY}

# enable debug reply on primary channel
# MESHTASTIC_CLIENT_FEATURES_ENABLEDEBUGREPLYONPRIMARYCHANNEL
meshtastic.client.features.enable-debug-reply-on-primary-channel: true
# enable gemini on private chat
# MESHTASTIC_CLIENT_FEATURES_ENABLEGEMINIONPRIVATECHAT
meshtastic.client.features.enable-gemini-on-private-chat: true
